CREATE TABLE "	" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "credit_usage_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"record_no" varchar(255) NOT NULL,
	"user_uuid" varchar(255) NOT NULL,
	"task_type" varchar(100) NOT NULL,
	"task_description" varchar(500),
	"credits_consumed" integer NOT NULL,
	"credits_remaining" integer NOT NULL,
	"task_status" varchar(50) NOT NULL,
	"external_task_id" varchar(255),
	"external_provider" varchar(100),
	"task_input" text,
	"task_output" text,
	"error_message" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	CONSTRAINT "credit_usage_records_record_no_unique" UNIQUE("record_no")
);